### ISSUE TITLE
not working on local

### ISSUE THREAD

**Issue by nathan-zhu** [kareemzok/jquery_event_calendar#1]
Hi, i'm try to use this module but seems not working, i follow all step to do it, can you help on it? thanks.

**Comment by kareemzok** [comment]
Hello , 
Can i know exactly what is the issue ? jquery error ? module error ? 
and note that u have to put the  module files  in jquery_event_calendar folder not in jquery_event_calendar-master 
and check if the library is installed correctly  at  /admin/reports/status

**Comment by kareemzok** [comment]
I closed this issue , if you still have problem , re-open it , or contact me by mail at kareemzok@gmail.com
